language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "node"
  - "lts/*"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - os: linux
      node_js: "lts/*"
      env: TEST_SUITE=coverage
    - os: linux
      node_js: "lts/*"
      env: TEST_SUITE=standard
script: npm run $TEST_SUITE
